### ISSUE TITLE
如何解决刷新query参数丢失的问题

### ISSUE THREAD

**Issue by peter-halo** [wukang0718/vueRouterEncryption#1]

**Comment by peter-halo** [comment]
当从A页面跳转到B页面，地址的参数成功加密，B页面也能成功获取到参数，但是在B页面执行刷新ctrl+r的浏览器刷新事件，地址栏的参数会丢失的问题，请问如何处理，是不是哪里使用或配置不正确导致的。

**Comment by wukang0718** [comment]
看一下你的代码

**Comment by wukang0718** [comment]
当从A页面跳转到B页面，B页面获取的参数并不是通过解密获取的，是vue-router在跳转路由的时候，直接合并的参数，
在B页面执行刷新ctrl+r的浏览器刷新的时候，会通过解密获取地址栏参数

**Comment by peter-halo** [comment]
我发现在页面刷新的时候，解密地址栏的参数的query = decrypt(query); 发生了异常，进入到了resolvePath 的异常分支。导致无法解析到参数。我重新更改了加密解密方法后，问题得到了解决。
 import CryptoJS from "crypto-js";
/**
 * 加密（需要先加载lib/aes/aes.min.js文件）
 */
export const encrypt = (word) => {
  var key = CryptoJS.enc.Utf8.parse("46cc793c53dc451b");
  var srcs = CryptoJS.enc.Utf8.parse(word);
  var encrypted = CryptoJS.AES.encrypt(srcs, key, {
    mode: CryptoJS.mode.ECB,
    padding: CryptoJS.pad.Pkcs7,
  });
  return encrypted.toString();
};
/**
 * 解密
 */
export const decrypt = (word) => {
  var key = CryptoJS.enc.Utf8.parse("46cc793c53dc451b");
  var decrypt = CryptoJS.AES.decrypt(word, key, {
    mode: CryptoJS.mode.ECB,
    padding: CryptoJS.pad.Pkcs7,
  });
  return CryptoJS.enc.Utf8.stringify(decrypt).toString();
};
然后问题就解决了

**Comment by wukang0718** [comment]
加密和解密的方法是对应的，我提供的示例中默认index.html是加载了crypto-js.min.js的
