### ISSUE TITLE
Malformed UTF-8 data

### ISSUE THREAD

**Issue by Andyczc** [wukang0718/vueRouterEncryption#2]
let url = stringifyQuery({
    diagnoseObjectId: 2,
    viewMode: 1,
    studentId: 2324,
    diagnosisId: 1,
  })

加密没有问题， 但是解密会报错，
另外  如果复制加密后的url路径   打开新的浏览器tab粘贴回车访问，就会报“Malformed UTF-8 data”

**Comment by wukang0718** [comment]
你能给我发一个示例吗？我给你查一下原因

**Comment by wukang0718** [comment]
这个报错是因为解密那一步的问题

**Comment by wukang0718** [comment]
比如你检查一下你的私钥是不是16位的啊

**Comment by JinnTao** [comment]
const decode = decodeURIComponent
decodeURIComponent ?这个函数在哪里呢？

**Comment by wukang0718** [comment]
这个不就是window上的方法

**Comment by JinnTao** [comment]
> 这个不就是window上的方法

....对哦
