### ISSUE TITLE
从别的系统需要跳转到我们的系统时，参数会怎么办？

### ISSUE THREAD

**Issue by yarkone** [wukang0718/vueRouterEncryption#3]
例如：需要跟B网站合作，进行传值操作。B网站使用明文传输给A网站，我们A网站是使用了这个参数解析，但是会发生参数丢失的问题。

例如：https://www.baidu.com  跳转 https://www.A.com?id=123456，那么我的A网站拿到的网址却是https://www.A.com，id直接丢失了

**Comment by wukang0718** [comment]
在`query.js` 61行，添加一个判断 `query` 是不是base64的函数
是 base64 在解密，不是base64不需要解密可以直接执行反序列化

判断是否base64的函数
```javascript
function isBase64(str) {
    if (str ==='' || str.trim() ===''){ return false; }
    try {
        return btoa(atob(str)) == str;
    } catch (err) {
        return false;
    }
}
```
仓库之后也会更新
