### ISSUE TITLE
地址栏如何初始状态就显示加密后的路径？

### ISSUE THREAD

**Issue by htharoldht** [wukang0718/vueRouterEncryption#4]
以下是录屏，初始状态下是未加密的，刷新后才显示加密

![录屏](https://user-images.githubusercontent.com/31093493/137256219-e4ffd3e3-8055-4e2d-a9dd-d3cbec3f6216.gif)

如何能够让初始状态下就显示加密啊？

**Comment by wukang0718** [comment]
`window.location.href = "http://localhost:8081/?foo=123"` 我使用这种方式打开的页面直接就是显示的加密的路径，你是怎么操作的

**Comment by htharoldht** [comment]
``` javascript
this.$router.push({
  path: 'xxx',
  query: { foo, bar },
})
```

> `window.location.href = "http://localhost:8081/?foo=123"` 我使用这种方式打开的页面直接就是显示的加密的路径，你是怎么操作的

**Comment by wukang0718** [comment]
我用和你一样的方式跳转是可以的，你能提供一个可以复现的完整代码吗？我查一下问题

**Comment by htharoldht** [comment]
我定位到问题了，是多级路由

MWE项目可见
链接：https://pan.baidu.com/s/1XH54xzvx9ER72zMmUEXPUA 
提取码：t1nw

**Comment by wukang0718** [comment]
![image](https://user-images.githubusercontent.com/42261663/138053193-0466578a-f27b-4869-b26e-0aca17c33211.png)
问题就出现在这一行，不知道你那边可不可以去掉这一行

**Comment by htharoldht** [comment]
好的，问题解决了，谢谢啦
